dev_addr: 127.0.0.1:8888

repo_url: https://github.com/redphx/better-xcloud
repo_name: Better xCloud

site_name: Better xCloud
site_url: https://better-xcloud.github.io
site_author: redphx
site_description: a short description of your website

nav:
  - Introduction: index.md
  - How to install:
    - 'Which client to use?': clients.md
    - Android app: android.md
    - Android browser: android-browser.md
    - Chrome/Edge: chromium.md
    - Safari: safari.md
    - LG TV: lg-webos.md
  - Features:
    - Global settings: features.md
    - Stream settings: ingame-features.md
    - Clarity boost: clarity-boost.md
    - Native Mouse & Keyboard: native-mouse-and-keyboard.md
    - Virtual controller: mouse-and-keyboard.md
    - Local co-op: local-co-op.md
    - Remote Play: remote-play.md
    - Stream stats: stream-stats.md
    - Screenshot capture: screenshot-capture.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md
  - Guides:
    - Android WebView tweaks: guide/android-webview-tweaks.md
    # - Switch Android WebView implementation: guide/android-webview-implementation.md
    - Nvidia SHIELD TV: guide/nvidia-shield-tv.md
  - ❤️ Donation: donation.md
  - Acknowledgements:
    - Acknowledgements: acknowledgements.md
    - Translators: translators.md

theme:
  name: material
  palette:
    scheme: slate
    primary: green
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.expand
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.expand

extra:
  social:
    - icon: simple/telegram
      link: https://t.me/betterxcloud
      name: Better xCloud on Telegram

    - icon: simple/kofi
      link: https://ko-fi.com/redphx
      name: Support Better xCloud on Ko-fi

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - redirects:
      redirect_maps:
        'browsers.md': clients.md
        'kiwi-browser.md': android-browser.md
